service: firebase
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true


functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: post
